In [5]:
import sys
import os

In [1]:
import imas

In [2]:
!imasdb test

export MDSPLUS_TREE_BASE_0=/home/fydev/public/imasdb/test/3/0 ;
export MDSPLUS_TREE_BASE_1=/home/fydev/public/imasdb/test/3/1 ;
export MDSPLUS_TREE_BASE_2=/home/fydev/public/imasdb/test/3/2 ;
export MDSPLUS_TREE_BASE_3=/home/fydev/public/imasdb/test/3/3 ;
export MDSPLUS_TREE_BASE_4=/home/fydev/public/imasdb/test/3/4 ;
export MDSPLUS_TREE_BASE_5=/home/fydev/public/imasdb/test/3/5 ;
export MDSPLUS_TREE_BASE_6=/home/fydev/public/imasdb/test/3/6 ;
export MDSPLUS_TREE_BASE_7=/home/fydev/public/imasdb/test/3/7 ;
export MDSPLUS_TREE_BASE_8=/home/fydev/public/imasdb/test/3/8 ;
export MDSPLUS_TREE_BASE_9=/home/fydev/public/imasdb/test/3/9 ;


In [5]:
os.getcwd()

'/workspaces/SpDM/examples'

In [6]:
%%writefile putslice_eq.py
# Definition of the class structures in file imas.py
import imas
import numpy
import sys
import os

'''
This sample program will create a pulse file (shot 13, run 1) and will
put an example of equilibirium IDS using put_slice methods.
'''

# This routine reads an array of pfsystems IDSs in the database, filling
# some fields of the IDSS

TEST_DATABASE_NAME='test'

def put_ids():
    """Class Itm is the main class for the UAL.

    It contains a set of field classes, each corresponding to a IDS
    defined in the UAL The parameters passed to this creator define the
    shot and run number. The second pair of arguments defines the
    reference shot and run and is used when the a new database is
    created, as in this example.

    """

    shot = 13
    time = 1
    interp = 1

    imas_obj = imas.ids(13, 1, 13, 1)
    imas_obj.create_env("fydev","test","3")  # Create a new instance of database

    if imas_obj.isConnected():
        print('Creation of data entry OK!') 
    else:
        print('Creation of data entry FAILED!')
        sys.exit()

    number = 10

    # Allocate a first generic vector and its time base
    lentime_1 = 3
    vect1DDouble_1 = numpy.empty([lentime_1])
    time_1 = numpy.empty([lentime_1])

    for i in range(lentime_1):
        time_1[i] = i
        vect1DDouble_1[i] = i * 10

    print ('========================================================')
    print( time_1)
    print (vect1DDouble_1)

    # Allocate a second generic vector and its time base
    lentime_2 = 4
    vect1DDouble_2 = numpy.empty([lentime_2])
    time_2 = numpy.empty([lentime_2])

    for i in range(lentime_2):
        time_2[i] = i
        vect1DDouble_2[i] = i * 11

    print ('========================================================')
    print (time_2)
    print (vect1DDouble_2)

    vect2DDouble_1 = numpy.zeros([3, 3])
    for i in range(3):
        for j in range(3):
                vect2DDouble_1[i, j] = i * 100 + j

    print ('========================================================')
    print (vect2DDouble_1)
    # Allocate a second generic vector and its time base
    lentime_2 = 4
    vect1DDouble_2 = numpy.empty([lentime_2])
    time_2 = numpy.empty([lentime_2])

    for i in range(lentime_2):
        time_2[i] = i
        vect1DDouble_2[i] = i * 11

    print('========================================================')
    print(time_2)
    print(vect1DDouble_2)

    vect2DDouble_1 = numpy.zeros([3, 3])
    for i in range(3):
        for j in range(3):
                vect2DDouble_1[i, j] = i * 100 + j

    print( '========================================================')
    print (vect2DDouble_1)

    vect2DDouble_2 = vect2DDouble_1 + 10000
    '''
        print( '========================================================')
        print( vect3DDouble_2)
        '''
    imas_obj.equilibrium.ids_properties.comment = 'This is a test ids'

    # A sample int

    # Mandatory to define this property
    imas_obj.equilibrium.ids_properties.homogeneous_time = 1
    imas_obj.equilibrium.resize(1)
    imas_obj.equilibrium.time_slice[0].profiles_2d.resize(2)
    imas_obj.equilibrium.time_slice[0].profiles_2d[
        0].Mesh_type.name = 'Mesh TYPE 1A'
    imas_obj.equilibrium.time_slice[0].profiles_2d[
        1].Mesh_type.name = 'Mesh TYPE 2B'

    imas_obj.equilibrium.time.resize(1)
    imas_obj.equilibrium.time_slice[0].profiles_2d[0].r.resize(3, 3)
    imas_obj.equilibrium.time_slice[0].profiles_2d[1].r.resize(3, 3)

    print( 'Start Put, writing first slice')
    imas_obj.equilibrium.time_slice[0].profiles_2d[0].r[:, 0] = vect2DDouble_1[0, :]
    imas_obj.equilibrium.time_slice[0].profiles_2d[1].r[:, 0] = vect2DDouble_2[0, :]
    imas_obj.equilibrium.time[0] = time_1[0]
    imas_obj.equilibrium.put()
    print ('Completed Put ')

    for i in range(lentime_1):
        print( '========================================================')
        print( 'vect3DDouble_1[i,:,:]')
        print (vect2DDouble_1[i, :])
        print ('========================================================')

        imas_obj.equilibrium.time_slice[0].profiles_2d[
            0].r[:, i] = vect2DDouble_1[i, :]
        print( '========================================================')
        print ('imas_obj.equilibrium.time_slice[0].profiles_2d[0].r')
        print (imas_obj.equilibrium.time_slice[0].profiles_2d[0].r[:, i])
        print ('========================================================')
        imas_obj.equilibrium.time_slice[0].profiles_2d[1].r[:, i] = vect2DDouble_2[i, :]
        imas_obj.equilibrium.time[0] = time_1[i]
        print (('Writing slice={0}'.format(i)))
        imas_obj.equilibrium.putSlice()

    print( '========================================================')
    print (imas_obj.equilibrium.time_slice[0].profiles_2d[0].r)

    '''
        print( '========================================================')
        print (imas_obj.equilibrium.time_slice[0].profiles_2d[1].r)
        '''
    imas_obj.close()


put_ids()

Writing putslice_eq.py


In [39]:
%run putslice_eq.py

Creation of data entry OK!
[0. 1. 2.]
[ 0. 10. 20.]
[0. 1. 2. 3.]
[ 0. 11. 22. 33.]
[[  0.   1.   2.]
 [100. 101. 102.]
 [200. 201. 202.]]
[0. 1. 2. 3.]
[ 0. 11. 22. 33.]
[[  0.   1.   2.]
 [100. 101. 102.]
 [200. 201. 202.]]
Start Put, writing first slice
Completed Put 
vect3DDouble_1[i,:,:]
[0. 1. 2.]
imas_obj.equilibrium.time_slice[0].profiles_2d[0].r
[0. 1. 2.]
Writing slice=0
vect3DDouble_1[i,:,:]
[100. 101. 102.]
imas_obj.equilibrium.time_slice[0].profiles_2d[0].r
[100. 101. 102.]
Writing slice=1
vect3DDouble_1[i,:,:]
[200. 201. 202.]
imas_obj.equilibrium.time_slice[0].profiles_2d[0].r
[200. 201. 202.]
Writing slice=2
[[  0. 100. 200.]
 [  1. 101. 201.]
 [  2. 102. 202.]]


In [57]:
%%writefile getslice_eq.py
# Definition of the class structures in file imas.py
import imas
import numpy
import sys
import os

'''
This sample program will open an existing pulse file
read the stored equilibrium IDSs.

It will then output the content of some fields of the equilibrium IDS.
'''

# This routine reads an array of pfsystems IDSs in the database, filling
# some fields of the IDSS

TEST_DATABASE_NAME='test'

def read_IDS():
    """Class Itm is the main class for the UAL.

    It contains a set of field classes, each corresponding to a IDS
    defined in the UAL The parameters passed to this creator define the
    shot and run number. The second pair of arguments defines the
    reference shot and run and is used when the a new database is
    created, as in this example.

    """
    my_ids_obj = imas.ids(13, 1, 13, 1)
    my_ids_obj.open_env("fydev","test","3")  # Create a new instance of database
    if my_ids_obj.isConnected():
        print( 'open OK!')
    else:
        print ('open FAILED!')
        sys.exit()

    my_ids_obj.equilibrium.getSlice(2.0, 1)
    # my_ids_obj.equilibrium.get()

    print ('========================================================')
    print ('ids_properties=')
    print( '   my_ids_obj.equilibrium.ids_properties.comment = ' +str (my_ids_obj.equilibrium.ids_properties.comment))
    print ('   my_ids_obj.equilibrium.ids_properties.homogeneous_time = ' + str(my_ids_obj.equilibrium.ids_properties.homogeneous_time))

    print( '========================================================')
    print( 'COILS')
    print( '========================================================')

    for iSlices in range(len(my_ids_obj.equilibrium.time_slice)):

        for iCoil in range(len(my_ids_obj.equilibrium.time_slice[iSlices].profiles_2d)):
            print( 'profiles_2d[' + str(iCoil) + '].name' + my_ids_obj.equilibrium.time_slice[iSlices].profiles_2d[iCoil].Mesh_type.name)
            print ('profiles_2d[' + str(iCoil) + '].profiles_2d.r:')
            print ('my_ids_obj.equilibrium.time_slice[iSlices].profiles_2d[iCoil].r')
            print('-------------')

    my_ids_obj.close()


read_IDS()

Overwriting getslice_eq.py


In [58]:
%run getslice_eq.py

open OK!
ids_properties=
   my_ids_obj.equilibrium.ids_properties.comment = This is a test ids
   my_ids_obj.equilibrium.ids_properties.homogeneous_time = 1
COILS
profiles_2d[0].name
profiles_2d[0].profiles_2d.r:
my_ids_obj.equilibrium.time_slice[iSlices].profiles_2d[iCoil].r
-------------
profiles_2d[1].name
profiles_2d[1].profiles_2d.r:
my_ids_obj.equilibrium.time_slice[iSlices].profiles_2d[iCoil].r
-------------


In [40]:
%%writefile put_pf.py
# Definition of the class structures in file imas.py
import imas
import numpy
import sys
import os
TEST_DATABASE_NAME='test'

def write_ids():
    """Class ids is the main class for the UAL.

    It contains a set of field classes, each corresponding to an IDS
    defined in the UAL

    """
    ids = imas.ids(12, 1, 12, 1)
    ids.create_env("fydev","test","3")  # Create a new instance of database
#       ids.enableMemCache()
    if ids.isConnected():
        print ('create OK!')
    else:
        print ('create FAILED!')
        sys.exit()
    number = 10  # number of elements
    ids.pf_active.ids_properties.comment = 'Test data'
    # A sample int
    # Mandatory to define this property
    ids.pf_active.ids_properties.homogeneous_time = 0
    ids.pf_active.coil.resize(2)
    ids.pf_active.coil[0].name = 'COIL 1A'
    ids.pf_active.coil[1].name = 'COIL 2B'
    ids.pf_active.coil[0].current.data.resize(number)
    ids.pf_active.coil[0].current.time.resize(number)
    for i in range(number):
        ids.pf_active.coil[0].current.data[i] = 2 * i
        ids.pf_active.coil[0].current.time[i] = i
    number = number + 2
    ids.pf_active.coil[1].current.data.resize(number)
    ids.pf_active.coil[1].current.time.resize(number)
    for i in range(number):
        ids.pf_active.coil[1].current.data[i] = 2 * i + 10
        ids.pf_active.coil[1].current.time[i] = i + number
    # Dump all CPO and CPOArray of the ids object. Very verbose !!
    print ('============================')
    print (ids.pf_active.coil[1])
    # Now the CPO array is filled, we store in the database via method put()
    ids.pf_active.put()
    print ('python program over')
write_ids()

Writing put_pf.py


In [41]:
%run put_pf.py

create OK!
class coilObj
Attribute name: COIL 2B
Attribute identifier: 
Attribute resistance: -9e+40
Attribute resistance_error_upper: -9e+40
Attribute resistance_error_lower: -9e+40
Attribute energy_limit_max: -9e+40
Attribute energy_limit_max_error_upper: -9e+40
Attribute energy_limit_max_error_lower: -9e+40
Attribute current_limit_max
[]
Attribute current_limit_max_error_upper
[]
Attribute current_limit_max_error_lower
[]
Attribute b_field_max
[]
Attribute b_field_max_error_upper
[]
Attribute b_field_max_error_lower
[]
Attribute temperature
[]
Attribute temperature_error_upper
[]
Attribute temperature_error_lower
[]
Attribute element
 	class element
Attribute current
 	class current
	Attribute data
	[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
	Attribute data_error_upper
	[]
	Attribute data_error_lower
	[]
	Attribute time
	[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]
Attribute voltage
 	class voltage
	Attribute data
	[]
	Attribute data_error_upper
	[]
	Attribute data_error

In [46]:
%%writefile  get_pf.py
# Definition of the class structures in file imas.py
import imas
import numpy
import sys
import os

'''
This sample program will open an existing pulse file (shot 123, run 3, created by script put_cpos.py) and will
read the stored (array of) equilibirium CPOs.

It will then output the content of some fields of the equilibrium CPOs.
'''

# This routine reads an array of pfsystems CPOs in the database, filling
# some fields of the CPOS

TEST_DATABASE_NAME='test'

def read_ids():
    """Class Itm is the main class for the UAL.

    It contains a set of field classes, each corresponding to a CPO
    defined in the UAL The parameters passed to this creator define the
    shot and run number. The second pair of arguments defines the
    reference shot and run and is used when the a new database is
    created, as in this example.

    """
    my_ids_obj = imas.ids(12, 1, 12, 1)
    my_ids_obj.open_env("fydev","test","3")  # Create a new instance of database

    if my_ids_obj.isConnected():
        print ('open OK!')
    else:
        print ('open FAILED!')
        sys.exit()

    my_ids_obj.pf_active.get()

    print ('========================================================')
    print ('ids_properties=')
    print ('   my_ids_obj.pf_active.ids_properties.comment = ' + my_ids_obj.pf_active.ids_properties.comment)
    print ('   my_ids_obj.pf_active.ids_properties.homogeneous_time = ' + str(my_ids_obj.pf_active.ids_properties.homogeneous_time))

    print ('========================================================')
    print ('COILS')
    print ('========================================================')

    for iCoil in range(len(my_ids_obj.pf_active.coil)):
        print ('coil[' + str(iCoil) + '].name' + my_ids_obj.pf_active.coil[iCoil].name)
        print ('coil[' + str(iCoil) + '].current.data:')
        print (my_ids_obj.pf_active.coil[iCoil].current.data)
        print ('coil[' + str(iCoil) + '].current.time:')
        print (my_ids_obj.pf_active.coil[iCoil].current.time)
        print('-------------')

    my_ids_obj.close()


read_ids()

Overwriting get_pf.py


In [47]:
%run get_pf.py

open OK!
ids_properties=
   my_ids_obj.pf_active.ids_properties.comment = Test data
   my_ids_obj.pf_active.ids_properties.homogeneous_time = 0
COILS
coil[0].nameCOIL 1A
coil[0].current.data:
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
coil[0].current.time:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
-------------
coil[1].nameCOIL 2B
coil[1].current.data:
[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
coil[1].current.time:
[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]
-------------
